version: "3.1"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'users_service'
